services:
  frontend:
    image: live-dashboard
    build: .
    ports:
      - "5173:5173"
    command: npm run host
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  todo-server:
    image: live-dashboard
    build: .
    ports:
      - "3000:3000"
    command: npm run todo
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
